# Generated by Django 5.0.1 on 2024-02-26 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HabitRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('value', models.CharField(max_length=30)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='habit_tracker.habit')),
            ],
        ),
        migrations.CreateModel(
            name='HabitUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('CALORIES', 'Calories'), ('COUNT', 'Count'), ('GR', 'Grams'), ('HR', 'Hours'), ('ITEMS', 'Items'), ('KG', 'Kilograms'), ('KM', 'Kilometers'), ('L', 'Litres'), ('M', 'Meters'), ('MILES', 'Miles'), ('MIN', 'Minutes'), ('ML', 'Mililitres'), ('PAGES', 'Pages'), ('PERCENTAGE', 'Percentage'), ('REPETITIONS', 'Repititions'), ('SEC', 'Seconds'), ('SERVINGS', 'Servings'), ('SETS', 'Sets'), ('STEPS', 'Steps'), ('WORDS', 'Words'), ('YES_NO', 'Yes / No')], max_length=30)),
                ('type', models.CharField(choices=[('INT', 'Integer'), ('FLOAT', 'Float'), ('BOOLEAN', 'Boolean'), ('TIME', 'Time')], max_length=20)),
            ],
            options={
                'unique_together': {('name', 'type')},
            },
        ),
        migrations.AddField(
            model_name='habit',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='habit_tracker.habitunit'),
        ),
    ]
